title: Data Science portfolio 
# logo: /assets/image.png
description: Adipisci sed labore porro amet aliquam. Ut neque dolore dolore consectetur. Consectetur labore modi sed numquam eius sit. Modi quaerat consectetur dolor etincidunt quaerat ut consectetur. Ipsum numquam quisquam adipisci velit numquam eius aliquam. Quiquia voluptatem voluptatem dolorem aliquam. Numquam magnam neque dolorem sit magnam. 
theme: jekyll-theme-minimal
include:
  - assets/css/styles.css

logo: <img src="assets/image.png" alt="Description of image" style="border-radius: 50%; width: 350px; height: 300px;">

