title: Data Science portfolio 
# logo: /assets/image.png
description: Tempora est quaerat quisquam dolor. Dolor labore aliquam dolore non adipisci ipsum quisquam. Dolorem ipsum ut non quiquia voluptatem etincidunt. Non quiquia labore quisquam ipsum. Quisquam modi tempora neque magnam quisquam.

Tempora est quaerat quisquam dolor. Dolor labore aliquam dolore non adipisci ipsum quisquam. Dolorem ipsum ut non quiquia voluptatem etincidunt. Non quiquia labore quisquam ipsum. Quisquam modi tempora neque magnam quisquam
show_downloads: true
theme: jekyll-theme-minimal
include:
  - assets/css/styles.css

logo: <img src="assets/image.png" alt="Description of image" style="border-radius: 50%; width: 350px; height: 300px;">

